version: '3.7'
services:
  tests:
    container_name: tests
    build: .
    image: myicpc/tests
    environment:
      HUB_URL: http://192.168.99.100:30303
    volumes:
    - maven:/root/.m2

volumes:
  maven: null
