version: '3.7'
services:
  hub:
    image: selenium/hub
    container_name: selenium_hub
    ports:
      - '4444:4444'
    networks:
      - selenium-grid
  chrome:
    image: selenium/node-chrome
    environment:
      HUB_HOST: hub
      HUB_PORT: 4444
    networks:
      - selenium-grid
  firefox:
    image: selenium/node-firefox
    environment:
      HUB_HOST: hub
      HUB_PORT: 4444
    networks:
      - selenium-grid

networks:
  selenium-grid:

volumes:
  maven:
