apiVersion: apps/v1
kind: Deployment
metadata:
  name: "hub-deployment"
  labels:
    role: "master"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "hub"
  template:
    metadata:
      labels:
        app: "hub"
    spec:
      containers:
        - name: "hub-container"
          image: "selenium/hub"
          ports:
            - containerPort: 4444