apiVersion: apps/v1
kind: Deployment
metadata:
  name: "node-firefox-deployment"
  labels:
    role: "slave"
spec:
  replicas: 5
  selector:
    matchLabels:
      app: "node-firefox"
  template:
    metadata:
      labels:
        app: "node-firefox"
    spec:
      containers:
        - name: "node-firefox-container"
          image: "selenium/node-firefox"
          env:
            - name: HUB_HOST
              value: "hub-service"
            - name: HUB_PORT
              value: "4444"
          resources:
            requests:
              cpu: "500m"