apiVersion: v1
kind: Service
metadata:
  name: "hub-service"
spec:
  ports:
    - port: 4444
      nodePort: 30303
      protocol: "TCP"
  selector:
    app: "hub"
  sessionAffinity: None
  type: NodePort
